"""Publish ModRelease findings as safe GitHub Actions annotations and a job summary."""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any

MAX_ANNOTATIONS = 50
SEVERITY_COMMAND = {"ERROR": "error", "WARNING": "warning", "INFO": "notice"}
_CONTROL_CHARS = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
_MARKDOWN_SPECIAL = re.compile(r"([\\`*_{}\[\]()#+.!|><:~-])")

def _clean_text(value: Any) -> str:
    """Flatten untrusted values into one line before writing workflow output."""
    text = str(value)
    text = _CONTROL_CHARS.sub(" ", text)
    return " ".join(text.replace("\r", " ").replace("\n", " ").split())

def escape_data(value: Any) -> str:
    """Escape workflow-command data so a finding cannot add another command."""
    return _CONTROL_CHARS.sub(" ", str(value)).replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")

def escape_property(value: Any) -> str:
    """Escape workflow-command properties, including delimiters between fields."""
    return escape_data(value).replace(":", "%3A").replace(",", "%2C")

def escape_markdown(value: Any) -> str:
    """Render untrusted paths as plain text in the job summary."""
    return _MARKDOWN_SPECIAL.sub(r"\\\1", _clean_text(value))

def _validate_report(payload: Any) -> tuple[list[dict[str, Any]], int, int, int]:
    if not isinstance(payload, dict) or not isinstance(payload.get("findings"), list):
        raise ValueError("report must be a JSON object with a findings array")
    findings: list[dict[str, Any]] = []
    for finding in payload["findings"]:
        if not isinstance(finding, dict):
            raise ValueError("each finding must be a JSON object")
        if not isinstance(finding.get("severity"), str) or not isinstance(finding.get("code"), str):
            raise ValueError("each finding must include string severity and code fields")
        findings.append(finding)
    counts = {level: sum(item["severity"].upper() == level for item in findings) for level in ("ERROR", "WARNING", "INFO")}
    return findings, counts["ERROR"], counts["WARNING"], counts["INFO"]

def _annotation(finding: dict[str, Any]) -> str:
    command = SEVERITY_COMMAND.get(finding["severity"].upper(), "notice")
    code = escape_data(finding["code"][:200])
    properties = []
    path = _clean_text(finding.get("path", ""))[:500]
    if path:
        properties.append(f"file={escape_property(path)}")
    properties.append(f"title={escape_property('ModRelease Studio: ' + code)}")
    message = escape_data(str(finding.get("message", "Finding reported by ModRelease Studio."))[:1000])
    return f"::{command} {','.join(properties)}::{message}"

def _summary(findings: list[dict[str, Any]], errors: int, warnings: int, infos: int) -> str:
    lines = ["## ModRelease Studio", "", f"**{errors} errors · {warnings} warnings · {infos} notices**", ""]
    if not findings:
        lines.append("No configured release checks reported a problem.")
    else:
        lines.extend(["| Severity | Check | File | Details |", "|---|---|---|---|"])
        for finding in findings[:MAX_ANNOTATIONS]:
            severity = escape_markdown(finding["severity"].upper())
            code = escape_markdown(finding["code"])
            path = escape_markdown(finding.get("path", "—"))
            message = escape_markdown(finding.get("message", "Finding reported by ModRelease Studio."))
            lines.append(f"| {severity} | `{code}` | `{path}` | {message} |")
        remaining = len(findings) - min(len(findings), MAX_ANNOTATIONS)
        if remaining:
            lines.extend(["", f"_Additional findings omitted from annotations and this summary: {remaining}._"])
    lines.extend(["", "Generated by [ModRelease Studio](https://github.com/GhosTnever-lkm/modrelease-studio).", ""])
    return "\n".join(lines)

def _write_summary(content: str) -> None:
    destination = os.environ.get("GITHUB_STEP_SUMMARY")
    if destination:
        with Path(destination).open("a", encoding="utf-8") as stream:
            stream.write(content)
    else:
        print(content)

def publish(report_path: str | Path, *, fail_on_warning: bool = False) -> int:
    path = Path(report_path)
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        findings, errors, warnings, infos = _validate_report(payload)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError):
        print("::error title=ModRelease Studio::Could not read a valid scan report; inspect the scan step output.")
        _write_summary("## ModRelease Studio\n\nThe scan report is missing or invalid. Check the scan step output.\n")
        return 2
    for finding in findings[:MAX_ANNOTATIONS]:
        print(_annotation(finding))
    _write_summary(_summary(findings, errors, warnings, infos))
    if fail_on_warning and warnings:
        print("::error title=ModRelease Studio::The report contains warnings and fail-on-warning is enabled.")
        return 1
    return 0

def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if len(args) != 1:
        print("Usage: annotate.py <report.json>", file=sys.stderr)
        return 2
    fail_on_warning = os.environ.get("FAIL_ON_WARNING", "false").strip().lower() == "true"
    return publish(args[0], fail_on_warning=fail_on_warning)

if __name__ == "__main__":
    raise SystemExit(main())
